---
title: ""
output:  
  bookdown::pdf_document2:
    toc: false
    number_sections: false
header-includes:
csl: apa.csl
bibliography: references.bib
---

# A generalizable tool for predicting developmental phenology for wild poikilotherms.

Morgan M. Sparks^1,3^, Brian C. Leavell^2^, Bryan M. Maitland^1^

^1^Rocky Mountain Research Station, U.S. Forest Service, Boise, Idaho, USA

^2^Smithsonian Tropical Research Institute, Apartado, Balboa, Ancón, Panamá

^3^Corresponding author, [Morgan.Sparks\@usda.gov](mailto:Morgan.Sparks@usda.gov){.email}

## Running title:

Predicting developmental phenology in the wild

## Acknowledgements

We thank N. Karraker, D. Pilliod, M. Hayes, R.B. Bury, and B. Norman for their help in translating sites for the tailed frog example to locations that could be aligned with COMIDs. D. Horan helped organize GPS locations into COMIDs. The views expressed in this manuscript are those of the authors and do not necessarily represent the views or policies of USFS . Any mention of trade names, products, or services does not imply an endorsement by the U.S. government or USFS. USFS does not endorse any commercial products, services or enterprises.

## Data Availability

**hatchR** is an open-source software environment distributed via CRAN and additional details hosted at software website (<https://bmait101.github.io/hatchR/>). Reproducible methods for this manuscript are available at the manuscript github (<https://github.com/morgan-sparks/hatchR_nonfish>) in the `paper.Rmd` file. The repository will become public and publicly archived with a DOI at acceptance of the manuscript.

## Conflict of interest

The authors declare no known conflict of interest.

## Author Contributions

Morgan Sparks and Bryan Maitland developed the software and conceived the manuscript. All authors collected data and wrote and edited the manuscript. This manuscript describes an application for software for poikilotherms. As such, it has no specific locale for data collection, however significant effort was made to represent a globally and taxonomically diverse set of species for case studies and model sources.
